/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "JenKnob.h"
#include "BackgroundImage.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class JenSx1000AudioProcessorEditor  :  public AudioProcessorEditor,
                                        public Slider::Listener,
                                        public Timer
{
public:
    JenSx1000AudioProcessorEditor (JenSx1000AudioProcessor&);
    ~JenSx1000AudioProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    
    void sliderValueChanged(Slider*) override;
    void sliderDragStarted(Slider*) override;
    void sliderDragEnded(Slider*) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    JenSx1000AudioProcessor& processor;
    
    BackgroundImage backgroundImage;
    
    JenSlider vcoVibrato, vcoPWM, vcoLevel, vcoGlide, lfoSpeed, vcfFrequency, vcfResonance, vcfLFO, vcfEnvLevel, vcfAttack, vcfDecay, vcfSustain, vcfRelease, noiseLevel, vcaOutputVolume, vcaAttack, vcaDecay, vcaSustain, vcaRelease;
    
    JenKnobTune vcoTune;
    JenKnobOctave vcoOctave;
    JenKnobNoise noiseNoise;
    JenKnobWaveform vcoWaveform;
    JenKnobPulseWidth vcoPulseWidth;

    
    JenSx1000AudioProcessor& getProcessor() const
    {
        return static_cast<JenSx1000AudioProcessor&> (processor);
    }
    
    AudioProcessorParameter* getParameterFromSlider (const Slider*) const;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (JenSx1000AudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
